blank_issues_enabled: true
contact_links:
  - name: 📋 Weekly Journal Help
    url: https://github.com/lseils/VIP-6600-Solar/.github/issues
    about: Have questions about using the weekly journal template?
